### ISSUE TITLE
MC_MUJOCO_SHARE_DESTINATION

### ISSUE THREAD

**Issue by fkanehiro** [rohanpsingh/mc_mujoco#45]
When I want to install `mc_mujoco` under my home directory, it seems that I need to change `CMAKE_INSTALL_PREFIX` and `MC_MUJOCO_SHARE_DESTINATION`. Is it necessary to make them configurable independently?

**Comment by rohanpsingh** [comment]
> When I want to install mc_mujoco under my home directory, it seems that I need to change `CMAKE_INSTALL_PREFIX` and `MC_MUJOCO_SHARE_DESTINATION`.

Really? In my case, only `CMAKE_INSTALL_PREFIX` is needed to be set. `MC_MUJOCO_SHARE_DESTINATION` is set [automatically](https://github.com/rohanpsingh/mc_mujoco/blob/main/CMakeLists.txt#L61).

**Comment by fkanehiro** [comment]
Maybe you specified `CMAKE_INSTALL_PREFIX` using `-D` option of `cmake`.
I ran `cmake` without specifying `CMAKE_INSTALL_PREFIX` and then changed `CMAKE_INSTALL_PREFIX` using `ccmake`.

**Comment by rohanpsingh** [comment]
Ah I see, yes I was using the `-D` option. I think we don't need to make `MC_MUJOCO_SHARE_DESTINATION` separately configurable as it is only used for storing xml models.

**Comment by gergondet** [comment]
That's because the variable were set as `CACHE` variable rather than regular variable and updating `CMAKE_INSTALL_PREFIX` after the first CMake run would not update them. I have made them regular variables in the above commit.

@fkanehiro note that mc_mujoco is available in https://github.com/mc-rtc/superbuild-extensions/ (but there is a little extra work to do to support MuJoCo on macOS automatically: https://github.com/mc-rtc/superbuild-extensions/blob/main/simulation/MuJoCo.cmake)

**Comment by fkanehiro** [comment]
Thanks, @gergondet !
